import marshmallow

class SquareSpaceInventorySchema(marshmallow.Schema):
    product_id = marshmallow.fields.String(missing=None)
    variant_id = marshmallow.fields.String(missing=None)
    product_type = marshmallow.fields.String(missing="SERVICE")
    product_page = marshmallow.fields.String(missing=None)
    product_url = marshmallow.fields.String(missing=None)
    title = marshmallow.fields.String(missing=None)
    description = marshmallow.fields.String(missing=None)
    sku = marshmallow.fields.String(missing=None)
    option_name_1 = marshmallow.fields.String(missing=None)
    option_value_1 = marshmallow.fields.String(missing=None)
    option_name_2 = marshmallow.fields.String(missing=None)
    option_value_2 = marshmallow.fields.String(missing=None)
    option_name_3 = marshmallow.fields.String(missing=None)
    option_value_3 = marshmallow.fields.String(missing=None)
    price = marshmallow.fields.Float(missing=None)
    sale_price = marshmallow.fields.Float(missing=None)
    on_sale = marshmallow.fields.String(missing="No", validate=marshmallow.validate.OneOf(["No", "Yes"]))
    stock = marshmallow.fields.Integer(missing=0)
    categories = marshmallow.fields.List(marshmallow.fields.String, missing=[])
    tags = marshmallow.fields.List(marshmallow.fields.String, missing=[])
    weight = marshmallow.fields.Float(missing=1.0)
    length = marshmallow.fields.Float(missing=0.0)
    width = marshmallow.fields.Float(missing=0.0)
    height = marshmallow.fields.Float(missing=0.0)
    visible = marshmallow.fields.String(missing="No", validate=marshmallow.validate.OneOf(["No", "Yes"]))
    image_url = marshmallow.fields.URL(missing=None)
